<p>
			<span style='float:right;'><a href='#'>Save or Load</a> &nbsp; | &nbsp; <a href='#'>Verify Against Major</a> &nbsp; | &nbsp; <a href='index.php'>Refresh</a></span>
			<span style='float:clear;'>
				Step one: 
				<select name="p_subj" id="p_subj">
					<option value="" selected="selected">Select a department</option>
					<option value="AFSC">Air Force Science (AFSC)
					</option><option value="ARCR">Americas Research Center (ARCR)
					</option><option value="ANTH">Anthropology (ANTH)
					</option><option value="ARAB">Arabic (ARAB)
					</option><option value="ARCH">Architecture (ARCH)
					</option><option value="ASIA">Asian Studies (ASIA)
					</option><option value="ASTR">Astronomy (ASTR)
					</option><option value="BIOC">Biochemistry &amp; Cell Biology (BIOC)

					</option><option value="BIOE">Bioengineering (BIOE)
					</option><option value="BUSI">Business (BUSI)
					</option><option value="CHBE">Chemical &amp; Biomolecular Eng (CHBE)
					</option><option value="CHEM">Chemistry (CHEM)
					</option><option value="CHIN">Chinese (CHIN)
					</option><option value="CEVE">Civil and Environmental Eng (CEVE)
					</option><option value="CLAS">Classical Studies (CLAS)
					</option><option value="CSCI">Cognitive Sciences (CSCI)
					</option><option value="COLL">College Course (COLL)
					</option><option value="COMM">Communication (COMM)
					</option><option value="CAAM">Comp. &amp; Applied Mathematics (CAAM)
					</option><option value="COMP">Computer Science (COMP)
					</option><option value="ESCI">Earth Science (ESCI)

					</option><option value="EBIO">Ecology &amp; Evolutionary Biology (EBIO)
					</option><option value="ECON">Economics (ECON)
					</option><option value="EDUC">Education (EDUC)
					</option><option value="ELEC">Electrical &amp; Comp. Engineering (ELEC)
					</option><option value="ENGI">Engineering (ENGI)
					</option><option value="ENGL">English (ENGL)
					</option><option value="ENST">Environment Studies (ENST)
					</option><option value="FILM">Film (FILM)
					</option><option value="FREN">French Studies (FREN)
					</option><option value="FSEM">Freshman Seminar (FSEM)
					</option><option value="GERM">German (GERM)
					</option><option value="GLHT">Global Health Technologies (GLHT)
					</option><option value="GREE">Greek (GREE)

					</option><option value="HEAL">Health Sciences (HEAL)
					</option><option value="HEBR">Hebrew (HEBR)
					</option><option value="HIND">Hindi (HIND)
					</option><option value="HIST">History (HIST)
					</option><option value="HART">History of Art (HART)
					</option><option value="HONS">Honors Program (HONS)
					</option><option value="HUMA">Humanities (HUMA)
					</option><option value="HURC">Humanities Research Center (HURC)
					</option><option value="ITAL">Italian Language and Culture (ITAL)
					</option><option value="JAPA">Japanese (JAPA)
					</option><option value="KECK">Keck Center (KECK)
					</option><option value="KINE">Kinesiology (KINE)
					</option><option value="KORE">Korean (KORE)
					</option><option value="LATI">Latin (LATI)
					</option><option value="LEAD">Leadership Rice (LEAD)
					</option><option value="MLSC">Liberal Studies Core/Capstone (MLSC)
					</option><option value="LPCR">Lifetime Phys Activity Credit (LPCR)

					</option><option value="LPAP">Lifetime Phys Activity Program (LPAP)
					</option><option value="LING">Linguistics (LING)
					</option><option value="MGMP">MBA for Professionals-Evening (MGMP)
					</option><option value="MGMW">MBA for Professionals-Weekend (MGMW)
					</option><option value="MGMT">Management (MGMT)
					</option><option value="MANA">Managerial Studies (MANA)
					</option><option value="MSCI">Materials Science (MSCI)
					</option><option value="MATH">Mathematics (MATH)
					</option><option value="MECH">Mechanical Engineering (MECH)
					</option><option value="MDST">Medieval Studies (MDST)
					</option><option value="MILI">Military Science (MILI)
					</option><option value="MUSI">Music (MUSI)
					</option><option value="NSCI">Natural Sciences (NSCI)
					</option><option value="NAVA">Naval Science (NAVA)
					</option><option value="NEUR">Neuroscience (NEUR)
					</option><option value="PHIL">Philosophy (PHIL)
					</option><option value="FOTO">Photography (FOTO)

					</option><option value="PHYS">Physics (PHYS)
					</option><option value="POST">Policy Studies (POST)
					</option><option value="POLI">Political Science (POLI)
					</option><option value="PORT">Portuguese (PORT)
					</option><option value="PSYC">Psychology (PSYC)
					</option><option value="RELI">Religious Studies (RELI)
					</option><option value="RUSS">Russian (RUSS)
					</option><option value="SOSC">Social Sciences (SOSC)
					</option><option value="SOCI">Sociology (SOCI)
					</option><option value="SPAN">Spanish (SPAN)
					</option><option value="SMGT">Sport Management (SMGT)
					</option><option value="STAT">Statistics (STAT)
					</option><option value="THEA">Theatre (THEA)
					</option><option value="TIBT">Tibetan (TIBT)
					</option><option value="UNIV">University Courses (UNIV)
					</option><option value="ARTS">Visual Arts (ARTS)
					</option><option value="SWGS">Women, Gender, &amp; Sexuality (SWGS)

					</option>
				</select>
				<a href='Javascript:changeDepartment();'>Select</a>
			</span>
		</p>